apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: springboot-app
  labels:
    app: spring-app
spec:
  selector:
    matchLabels:
      app: spring-app
  replicas: 1 
  template:
    metadata:
      labels:
        app: spring-app
    spec:
      containers:
        - name: spring-app
          image: IMAGENAME
          ports:
            - containerPort: 8090
      imagePullSecrets:
        - name: jfrog-creds

---
apiVersion: v1
kind: Service
metadata:
  name: springboot-service
spec:
  selector:
    app: spring-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8090
  type: NodePort
